doctrine:
    dbal:
        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType
            geography:
                class: 'Jsor\Doctrine\PostGIS\Types\GeographyType'
                commented: false
            geometry:
                class: 'Jsor\Doctrine\PostGIS\Types\GeometryType'
                commented: false
            raster:
                class: 'Jsor\Doctrine\PostGIS\Types\RasterType'
                commented: false
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
    orm:
        dql:
            string_functions:
                Geography: Jsor\Doctrine\PostGIS\Functions\Geography
                ST_DWITHIN: Jsor\Doctrine\PostGIS\Functions\ST_DWithin
                ST_Distance: Jsor\Doctrine\PostGIS\Functions\ST_Distance
                ST_Point: Jsor\Doctrine\PostGIS\Functions\ST_Point
                ST_SetSRID: Jsor\Doctrine\PostGIS\Functions\ST_SetSRID
                ST_Transform: Jsor\Doctrine\PostGIS\Functions\ST_Transform
                ST_GeometryFromText:      Jsor\Doctrine\PostGIS\Functions\ST_GeomFromText
                ST_GeographyFromText: Jsor\Doctrine\PostGIS\Functions\ST_GeographyFromText

        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

